name: 🐞 Bug Report
description: File a new bug report
title: '[Bug]: <title>'
labels: 
  - "bug"
  - "triage"
assignees:
  - "norwoodj"
  - "Nepo26"
body:
  - type: markdown
    attributes:
      value: 'Thanks for taking the time to fill out this bug report!'
  - type: checkboxes
    attributes:
      label: 'Is there an existing issue for this?'
      description: 'Please [search :mag: the issues](https://github.com/ramondeklein/helm-docs/issues) to check if this bug has already been reported.'
      options:
        - label: 'I have searched the existing issues'
          required: true
  - type: textarea
    attributes:
      label: 'Current Behavior'
      description: 'Describe the problem you are experiencing.  **Please do not paste your logs here.**  Screenshots are welcome.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Expected Behavior'
      description: 'Describe what you expect to happen instead.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Reference Chart'
      description: |
        Please provide an example chart, be it the full code or just a reference to a repository.
        
        > OBS.: :warning: _Remember to redact or remove any sensitive information!_
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Reference Template'
      description: |
        If you are using a custom template, put it in here, so we can help you better.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 'Environment'
      description: 'Please provide the following information about your environment; feel free to remove any items which are not relevant.'
      value: |
        - Operating system:
        - Helm version (output of `helm version`):
        - GO version (output of `go version`):
        - Method of calling `helm-docs` (manual, jenkins, github action ...):
#TODO Add when the version function is implemented:
# - **helm-docs** version (output of `helm-docs version`):
    validations:
      required: false
  - type: input
    attributes:
      label: 'Link to `helm-docs` Logs'
      description: |
        Create a [Gist](https://gist.github.com)—which contains your _full_ `helm-docs` logs—and link it here.  Alternatively, you can attach a logfile to this issue (drag it into the "Further Information" field below).
        
        Remember to use the following flag `--log-level debug`
        
        > OBS.: :warning: _Remember to redact or remove any sensitive information!_
      placeholder: 'https://gist.github.com/...'
    validations:
      required: false
  - type: textarea
    attributes:
      label: Further Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        _Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in._
    validations:
      required: false
  - type: markdown
    attributes:
      value: ':stop_sign: _For support questions, you may create an issue with the question template._'
